modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/LatvianModder/Item-Filters/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "itemfilters"
version = "${version}"
displayName = "Item Filters"
authors = "LatvianModder"
description = '''
Adds Item Filters that can be used in other mods to filter multiple items in devices
'''
license = "GNU LGPLv3"

[[dependencies.itemfilters]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemfilters]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemfilters]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"
